import { 
  Profile, 
  UG, 
  Area, 
  Linha, 
  CentroTrabalho, 
  Equipamento, 
  Ocorrencia, 
  Peca, 
  Orcamento, 
  Anexo, 
  OcorrenciaEvento, 
  Manutencao, 
  LevantamentoLegado 
} from '../types/database';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-adriano',
    email: 'adriano.pinto@visioncontrols.com.br',
    nome: 'Adriano Coelho Pinto',
    cargo: 'Diretor / Engenheiro Chefe',
    role: 'ADMIN',
    empresa: 'VISION CONTROLS',
    telefone: '+55 21 98844-1234',
    ativo: true,
  },
  {
    id: 'user-luiz',
    email: 'luiz.pereira@visioncontrols.com.br',
    nome: 'Luiz Pereira',
    cargo: 'Gestor de Contrato & Planejamento',
    role: 'GESTOR',
    empresa: 'VISION CONTROLS',
    telefone: '+55 21 99762-5678',
    ativo: true,
  },
  {
    id: 'user-arthur',
    email: 'arthur.almeida@visioncontrols.com.br',
    nome: 'Arthur Almeida',
    cargo: 'Encarregado de Campo & Refrigeração',
    role: 'ENCARREGADO',
    empresa: 'VISION CONTROLS',
    telefone: '+55 21 97123-9988',
    ativo: true,
  },
  {
    id: 'user-alan',
    email: 'alan.silva@visioncontrols.com.br',
    nome: 'Alan Silva',
    cargo: 'Técnico de Campo Climatização',
    role: 'TECNICO',
    empresa: 'VISION CONTROLS',
    telefone: '+55 21 98455-4321',
    ativo: true,
  },
  {
    id: 'user-ambev-vis',
    email: 'auditoria.fabril@ambev.com.br',
    nome: 'Engenharia de Utilidades AMBEV',
    cargo: 'Engenheiro de Confiabilidade',
    role: 'VISUALIZADOR',
    empresa: 'AMBEV',
    telefone: '+55 21 99999-5544',
    ativo: true,
  },
];

export const INITIAL_UGS: UG[] = [
  { id: 'ug-n1', codigo: 'N1', nome: 'UG N1 — Embalagem e Linhas de Envase', descricao: 'Área fabril de linhas de alta velocidade de cerveja e refrigerante', ordem: 1 },
  { id: 'ug-n2', codigo: 'N2', nome: 'UG N2 — Fabricação, Fermentação e Maturação', descricao: 'Salas de brassagem, fermentadores e adegas de cerveja', ordem: 2 },
  { id: 'ug-n3', codigo: 'N3', nome: 'UG N3 — Utilidades e Subestações', descricao: 'Central de ar comprimido, amônia, chillers centrais e subestação elétrica', ordem: 3 },
  { id: 'ug-n4', codigo: 'N4', nome: 'UG N4 — Expansão Fabril Futura', descricao: 'Galpão em estruturação para novas linhas de envase', ordem: 4 },
];

export const INITIAL_AREAS: Area[] = [
  { id: 'area-1', ug_id: 'ug-n1', codigo: 'EMB-RET', nome: 'Retornáveis (Vidro)' },
  { id: 'area-2', ug_id: 'ug-n1', codigo: 'EMB-OWC', nome: 'One Way Cerveja (Lata)' },
  { id: 'area-3', ug_id: 'ug-n1', codigo: 'EMB-OWR', nome: 'One Way Refri (PET)' },
  { id: 'area-4', ug_id: 'ug-n2', codigo: 'FAB-CRV', nome: 'Fabricação Cerveja' },
  { id: 'area-5', ug_id: 'ug-n2', codigo: 'XAR-REF', nome: 'Xaroparia' },
  { id: 'area-6', ug_id: 'ug-n3', codigo: 'UTI-IND', nome: 'Utilidades e Frio Industrial' },
  { id: 'area-7', ug_id: 'ug-n3', codigo: 'ADM-LAB', nome: 'Administrativo e Laboratórios' },
];

export const INITIAL_LINHAS: Linha[] = [
  { id: 'linha-101', area_id: 'area-1', codigo: 'L101', nome: 'Linha 101 — Vidro Retornável 600ml', codigo_sap: 'LIN-501-VID' },
  { id: 'linha-102', area_id: 'area-2', codigo: 'L102', nome: 'Linha 102 — Latas Cerveja 350ml/473ml', codigo_sap: 'LIN-502-LAT' },
  { id: 'linha-103', area_id: 'area-3', codigo: 'L103', nome: 'Linha 103 — PET Refrigerante 2L', codigo_sap: 'LIN-503-PET' },
  { id: 'linha-104', area_id: 'area-1', codigo: 'L104', nome: 'Linha 104 — Garrafas Long Neck 330ml', codigo_sap: 'LIN-504-LNK' },
  { id: 'linha-105', area_id: 'area-2', codigo: 'L105', nome: 'Linha 105 — Chopp Barril', codigo_sap: 'LIN-505-CHP' },
  { id: 'linha-201', area_id: 'area-4', codigo: 'L201', nome: 'Linha 201 — Sala de Brassagem 1 & 2', codigo_sap: 'LIN-201-BRS' },
  { id: 'linha-202', area_id: 'area-4', codigo: 'L202', nome: 'Linha 202 — Adegas e Filtração Cerveja', codigo_sap: 'LIN-202-ADG' },
  { id: 'linha-301', area_id: 'area-5', codigo: 'L301', nome: 'Linha 301 — Mistura e Xaroparia Contínua', codigo_sap: 'LIN-301-XAR' },
  { id: 'linha-401', area_id: 'area-6', codigo: 'L401', nome: 'Linha 401 — Casa de Compressores e Chillers', codigo_sap: 'LIN-401-UTI' },
  { id: 'linha-402', area_id: 'area-6', codigo: 'L402', nome: 'Linha 402 — Tratamento de Água (ETA/ETDI)', codigo_sap: 'LIN-402-ETA' },
  { id: 'linha-403', area_id: 'area-6', codigo: 'L403', nome: 'Linha 403 — Subestação Elétrica Geral 13.8kV', codigo_sap: 'LIN-403-SUB' },
  { id: 'linha-501', area_id: 'area-7', codigo: 'L501', nome: 'Linha 501 — Prédio Central e Sala de Controle (COS)', codigo_sap: 'LIN-501-COS' },
  { id: 'linha-502', area_id: 'area-7', codigo: 'L502', nome: 'Linha 502 — Laboratórios Físico-Químicos e Microbiologia', codigo_sap: 'LIN-502-LAB' },
];

export const INITIAL_CENTROS_TRABALHO: CentroTrabalho[] = [
  { id: 'ct-1', linha_id: 'linha-101', nome: 'Decoradora Fuhrmeister', codigo_sap: 'CT-DEC-01', descricao: 'Máquina de rotulagem e decoração de garrafas' },
  { id: 'ct-2', linha_id: 'linha-101', nome: 'Enchedora Krones Lavatec', codigo_sap: 'CT-ENC-01', descricao: 'Enchedora isobárica de alta capacidade' },
  { id: 'ct-3', linha_id: 'linha-101', nome: 'Painel Principal CCM 01', codigo_sap: 'CT-CCM-101', descricao: 'Painel elétrico de controle de motores' },
  { id: 'ct-4', linha_id: 'linha-102', nome: 'Recravadora Ferrum', codigo_sap: 'CT-REC-02', descricao: 'Recravação de tampas em latas de alumínio' },
  { id: 'ct-5', linha_id: 'linha-102', nome: 'Enchedora KHS Innofill', codigo_sap: 'CT-ENC-02', descricao: 'Enchedora rotativa de latas' },
  { id: 'ct-6', linha_id: 'linha-103', nome: 'Sopradora Sidel Matrix', codigo_sap: 'CT-SOP-03', descricao: 'Sopradora de pré-formas PET' },
  { id: 'ct-7', linha_id: 'linha-103', nome: 'Rotuladora Krones Contiroll', codigo_sap: 'CT-ROT-03', descricao: 'Rotulagem de garrafas PET' },
  { id: 'ct-8', linha_id: 'linha-401', nome: 'Chiller Central 01 REFRIAC', codigo_sap: 'CT-CHL-01', descricao: 'Resfriamento de glicol para processo fabril' },
  { id: 'ct-9', linha_id: 'linha-401', nome: 'Chiller Central 02 YORK', codigo_sap: 'CT-CHL-02', descricao: 'Resfriamento de água gelada industrial' },
  { id: 'ct-10', linha_id: 'linha-403', nome: 'Sala do Painel Média Tensão', codigo_sap: 'CT-SUB-01', descricao: 'Painéis de manobra 13.8kV' },
  { id: 'ct-11', linha_id: 'linha-501', nome: 'Sala dos Servidores TI / COS', codigo_sap: 'CT-TI-01', descricao: 'Data center local da fábrica e automação' },
  { id: 'ct-12', linha_id: 'linha-502', nome: 'Lab Central Cromatografia', codigo_sap: 'CT-LAB-01', descricao: 'Ambiente estéril climatizado 20°C +/- 1°C' },
];

export const INITIAL_EQUIPAMENTOS: Equipamento[] = [
  {
    id: 'equip-360',
    tag: '360',
    patrimonio: 'PAT-AMB-00360',
    tag_sap: 'ACO-L101-DEC-01',
    tipo: 'CPE porta',
    marca: 'RITTAL',
    modelo: 'TopTherm Blue e+ SK 3186.930',
    numero_serie: 'SN-RIT-2022-9481',
    capacidade: '2.000 W (6.800 BTU/h)',
    tensao: '230V 1F',
    corrente: '5.2A',
    gas_refrigerante: 'R-134a',
    ano_fabricacao: 2022,
    ppac: 'PPAC-MENSAL-CPE',
    ug_id: 'ug-n1',
    area_id: 'area-1',
    linha_id: 'linha-101',
    centro_trabalho_id: 'ct-1',
    sublocal: 'Painel de Comando PLC da Decoradora',
    status: 'PARADO',
    observacoes: 'Compressor travado após sobretensão na rede da esteira. Ocorrência aberta para troca de ventoinha e relé térmico.',
    qr_slug: 'ivca-eq-360',
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'equip-223',
    tag: '223',
    patrimonio: 'PAT-AMB-00223',
    tag_sap: 'ACO-UTI-CHL-01',
    tipo: 'Chiller',
    marca: 'REFRIAC',
    modelo: 'RAF-120-SC Industrial',
    numero_serie: 'SN-REF-2019-4820',
    capacidade: '120 TR (1.440.000 BTU/h)',
    tensao: '380V 3F',
    corrente: '185A',
    gas_refrigerante: 'R-410A',
    ano_fabricacao: 2019,
    ppac: 'PPAC-SEMESTRAL-CHILLER',
    ug_id: 'ug-n3',
    area_id: 'area-6',
    linha_id: 'linha-401',
    centro_trabalho_id: 'ct-8',
    sublocal: 'Base metálica externa Utilidades',
    status: 'PARADO',
    observacoes: 'Vazamento no circuito 2 e queima da contatora principal. Aguardando aprovação do orçamento pela gerência AMBEV.',
    qr_slug: 'ivca-eq-223',
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'equip-104',
    tag: '104',
    patrimonio: 'PAT-AMB-00104',
    tag_sap: 'ACO-L102-REC-01',
    tipo: 'CPE teto',
    marca: 'KRONES',
    modelo: 'SK-TopClima 1500',
    numero_serie: 'SN-KRN-2021-1120',
    capacidade: '1.500 W',
    tensao: '400V 2F',
    corrente: '4.1A',
    gas_refrigerante: 'R-134a',
    ano_fabricacao: 2021,
    ppac: 'PPAC-MENSAL-CPE',
    ug_id: 'ug-n1',
    area_id: 'area-2',
    linha_id: 'linha-102',
    centro_trabalho_id: 'ct-4',
    sublocal: 'Teto do Gabinete Recravadora',
    status: 'RESTRICAO',
    observacoes: 'Operando com 1 dos 2 microventiladores internos com ruído excessivo de rolamento. Monitorando temperatura.',
    qr_slug: 'ivca-eq-104',
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'equip-115',
    tag: '115',
    patrimonio: 'PAT-AMB-00115',
    tag_sap: 'ACO-L101-ENC-01',
    tipo: 'CPE porta',
    marca: 'RITTAL',
    modelo: 'SK 3304.500 Blue e',
    numero_serie: 'SN-RIT-2023-3392',
    capacidade: '1.100 W',
    tensao: '230V 1F',
    corrente: '3.8A',
    gas_refrigerante: 'R-134a',
    ano_fabricacao: 2023,
    ppac: 'PPAC-MENSAL-CPE',
    ug_id: 'ug-n1',
    area_id: 'area-1',
    linha_id: 'linha-101',
    centro_trabalho_id: 'ct-2',
    sublocal: 'Porta frontal CCM Enchedora',
    status: 'OK',
    observacoes: 'Limpeza de filtros e medição de corrente realizada na preventiva de fevereiro/2026. Parâmetros normais.',
    qr_slug: 'ivca-eq-115',
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'equip-189',
    tag: '189',
    patrimonio: 'PAT-AMB-00189',
    tag_sap: 'ACO-L103-SOP-01',
    tipo: 'Splitão',
    marca: 'CARRIER',
    modelo: '40GKX060',
    numero_serie: 'SN-CAR-2020-8812',
    capacidade: '60.000 BTU/h (5 TR)',
    tensao: '380V 3F',
    corrente: '14.5A',
    gas_refrigerante: 'R-410A',
    ano_fabricacao: 2020,
    ppac: 'PPAC-TRIMESTRAL-SPLITAO',
    ug_id: 'ug-n1',
    area_id: 'area-3',
    linha_id: 'linha-103',
    centro_trabalho_id: 'ct-6',
    sublocal: 'Plataforma superior Sopradora Sidel',
    status: 'OK',
    observacoes: 'Higienização da serpentina evaporadora realizada em 15/02/2026. Delta T = 11.5°C.',
    qr_slug: 'ivca-eq-189',
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'equip-402',
    tag: '402',
    patrimonio: 'PAT-AMB-00402',
    tag_sap: 'ACO-UTI-SUB-01',
    tipo: 'Self Contained',
    marca: 'HITACHI',
    modelo: 'RPC-100T3',
    numero_serie: 'SN-HIT-2018-0914',
    capacidade: '10 TR',
    tensao: '380V 3F',
    corrente: '22A',
    gas_refrigerante: 'R-407C',
    ano_fabricacao: 2018,
    ppac: 'PPAC-MENSAL-SELF',
    ug_id: 'ug-n3',
    area_id: 'area-6',
    linha_id: 'linha-403',
    centro_trabalho_id: 'ct-10',
    sublocal: 'Sala Elétrica 13.8kV',
    status: 'OK',
    observacoes: 'Substituição das correias de transmissão e filtro de ar G4 na última preventiva.',
    qr_slug: 'ivca-eq-402',
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'equip-501',
    tag: '501',
    patrimonio: 'PAT-AMB-00501',
    tag_sap: 'ACO-ADM-TI-01',
    tipo: 'Fan Coil de Precisão',
    marca: 'LIEBERT / VERTIV',
    modelo: 'HPM S23E',
    numero_serie: 'SN-LIE-2022-7711',
    capacidade: '23 kW',
    tensao: '380V 3F',
    corrente: '38A',
    gas_refrigerante: 'R-410A',
    ano_fabricacao: 2022,
    ppac: 'PPAC-MENSAL-PRECISAO',
    ug_id: 'ug-n3',
    area_id: 'area-7',
    linha_id: 'linha-501',
    centro_trabalho_id: 'ct-11',
    sublocal: 'Data Center COS',
    status: 'OK',
    observacoes: 'Redundância N+1 com equipamento 502. Temperatura mantida em 21.0°C constante.',
    qr_slug: 'ivca-eq-501',
    created_at: '2025-01-10T08:00:00Z',
  },
];

// Generate the remaining 174 OK equipments to complete the exact 181 park
for (let i = 1; i <= 174; i++) {
  const tagNum = 1000 + i;
  const marcas = ['RITTAL', 'KRONES', 'YORK', 'CARRIER', 'REFRIAC', 'SPRINGER', 'DAIKIN'];
  const tipos = ['CPE porta', 'CPE teto', 'Splitão', 'Chiller', 'Fan Coil', 'Self Contained'];
  const ugs = ['ug-n1', 'ug-n2', 'ug-n3'];
  const areas = ['area-1', 'area-2', 'area-3', 'area-4', 'area-5', 'area-6', 'area-7'];
  const linhas = ['linha-101', 'linha-102', 'linha-103', 'linha-104', 'linha-105', 'linha-201', 'linha-202', 'linha-301', 'linha-401', 'linha-402', 'linha-403', 'linha-501', 'linha-502'];
  const cts = ['ct-1', 'ct-2', 'ct-3', 'ct-4', 'ct-5', 'ct-6', 'ct-7', 'ct-8', 'ct-9', 'ct-10', 'ct-11', 'ct-12'];

  INITIAL_EQUIPAMENTOS.push({
    id: `equip-${tagNum}`,
    tag: `${tagNum}`,
    patrimonio: `PAT-AMB-${tagNum}`,
    tag_sap: `ACO-SAP-${tagNum}`,
    tipo: tipos[i % tipos.length],
    marca: marcas[i % marcas.length],
    modelo: `Industrial Mod-${(i % 12) + 10}`,
    numero_serie: `SN-${marcas[i % marcas.length].substring(0, 3)}-2023-${1000 + i}`,
    capacidade: i % 2 === 0 ? '30.000 BTU/h' : '1.500 W',
    tensao: i % 3 === 0 ? '380V 3F' : '230V 1F',
    corrente: `${(3.5 + (i % 15) * 0.8).toFixed(1)}A`,
    gas_refrigerante: i % 2 === 0 ? 'R-410A' : 'R-134a',
    ano_fabricacao: 2018 + (i % 6),
    ppac: 'PPAC-PREV-2026',
    ug_id: ugs[i % ugs.length],
    area_id: areas[i % areas.length],
    linha_id: linhas[i % linhas.length],
    centro_trabalho_id: cts[i % cts.length],
    sublocal: `Módulo fabril ${((i % 8) + 1)}`,
    status: 'OK',
    observacoes: 'Equipamento inspecionado com rotina preventiva em dia.',
    qr_slug: `ivca-eq-${tagNum}`,
    created_at: '2025-01-10T08:00:00Z',
  });
}

export const INITIAL_OCORRENCIAS: Ocorrencia[] = [
  {
    id: 'ocor-360',
    numero: 1042,
    equipamento_id: 'equip-360',
    tipo_servico: 'CORRETIVA',
    criticidade: 'CRITICA',
    status: 'ABERTA',
    data_avaria: '2026-08-17T09:30:00Z', // 8 days ago
    previsao_retorno: '2026-08-28T18:00:00Z',
    relatante_nome: 'Arthur Almeida',
    relatante_id: 'user-arthur',
    tecnico_responsavel_id: 'user-alan',
    tecnico_responsavel_nome: 'Alan Silva',
    descricao_anomalia: 'CPE da porta frontal do painel principal da Decoradora Fuhrmeister desarmou por sobretemperatura (código E01). Compressor travado e ventoinha axial externa danificada.',
    causa_provavel: 'Pico de tensão e alta concentração de umidade com poeira de vidro na serpentina do condensador.',
    nota_sap: '10098421',
    ordem_sap: '40019284',
    ordem_vision: 'VC-2026-089',
    ppac: 'PPAC-CORRETIVA-EMERGENCIAL',
    equipamento_parado: true,
    parou_linha: true,
    created_at: '2026-08-17T10:00:00Z',
  },
  {
    id: 'ocor-223',
    numero: 1038,
    equipamento_id: 'equip-223',
    tipo_servico: 'CORRETIVA',
    criticidade: 'ALTA',
    status: 'AGUARDANDO_APROVACAO_AMBEV',
    data_avaria: '2026-08-03T14:00:00Z', // 22 days ago
    previsao_retorno: '2026-08-30T17:00:00Z',
    relatante_nome: 'Luiz Pereira',
    relatante_id: 'user-luiz',
    tecnico_responsavel_id: 'user-alan',
    tecnico_responsavel_nome: 'Alan Silva',
    descricao_anomalia: 'Chiller Central 01 REFRIAC apresentou perda de carga de refrigerante no circuito B e contatora tripada com desgaste severo de platinados.',
    causa_provavel: 'Vibração contínua na tubulação de descarga causando trinca por fadiga na curva de cobre de 1 1/8".',
    nota_sap: '10097115',
    ordem_sap: '40018902',
    ordem_vision: 'VC-2026-074',
    ppac: 'PPAC-CORRETIVA-CHILLER',
    equipamento_parado: true,
    parou_linha: false,
    created_at: '2026-08-03T15:30:00Z',
  },
];

export const INITIAL_PECAS: Peca[] = [
  {
    id: 'peca-1',
    ocorrencia_id: 'ocor-223',
    descricao: 'Contatora Tripolar 250A 220Vca para Compressor Scroll',
    part_number: 'LC1D150M7',
    fabricante: 'Schneider Electric',
    quantidade: 2,
    unidade: 'UN',
    fornecedor: 'TermoService RJ & Automação',
    valor_unitario: 3850.00,
    previsao_entrega: '2026-08-29',
    status: 'COTACAO',
    created_at: '2026-08-04T11:00:00Z',
  },
  {
    id: 'peca-2',
    ocorrencia_id: 'ocor-223',
    descricao: 'Gás Refrigerante Ecológico R-410A Cilindro 11.3kg',
    part_number: 'R410A-DAC',
    fabricante: 'Chemours / Dupont',
    quantidade: 4,
    unidade: 'CX',
    fornecedor: 'Dufrio Refrigeração Industrial',
    valor_unitario: 1787.50,
    previsao_entrega: '2026-08-28',
    status: 'COTACAO',
    created_at: '2026-08-04T11:15:00Z',
  },
  {
    id: 'peca-3',
    ocorrencia_id: 'ocor-360',
    descricao: 'Motor Ventilador Axial 230V 50/60Hz SK Blue e+',
    part_number: 'SK 3397.524',
    fabricante: 'RITTAL',
    quantidade: 1,
    unidade: 'UN',
    fornecedor: 'Rittal Brasil Distribuidor',
    valor_unitario: 2450.00,
    previsao_entrega: '2026-08-27',
    status: 'SOLICITADA',
    created_at: '2026-08-17T11:30:00Z',
  },
];

export const INITIAL_ORCAMENTOS: Orcamento[] = [
  {
    id: 'orc-1',
    ocorrencia_id: 'ocor-223',
    numero: 'ORC-2026-0418-REV2',
    fornecedor: 'TermoService RJ & Automação Ltda',
    valor_total: 14850.00,
    data_envio: '2026-08-05T16:00:00Z',
    enviado_para: 'Engenharia de Utilidades AMBEV (Eng. Marcos Silveira)',
    validade: '2026-09-05',
    status: 'ENVIADO',
    arquivo_pdf_url: 'https://visioncontrols.com.br/docs/orcamentos/ORC-2026-0418.pdf',
    observacoes: 'Orçamento com frete CIF incluso na fábrica AMBEV Campo Grande RJ e mão de obra de solda oxiacetilênica com teste de estanqueidade a N2.',
    created_at: '2026-08-05T16:20:00Z',
  },
  {
    id: 'orc-2',
    ocorrencia_id: 'ocor-360',
    numero: 'ORC-2026-0817-REV1',
    fornecedor: 'Rittal Sistemas Eletromecânicos Brasil',
    valor_total: 8920.00,
    data_envio: '2026-08-17T11:00:00Z',
    enviado_para: 'PCM Envase AMBEV (Fabiano Costa)',
    validade: '2026-09-17',
    status: 'EM_ANALISE',
    arquivo_pdf_url: 'https://visioncontrols.com.br/docs/orcamentos/ORC-2026-0817.pdf',
    observacoes: 'Fornecimento de motor axial de reposição original Rittal SK 3397.524 e conjunto de filtros sintéticos para painel CLP.',
    created_at: '2026-08-17T11:30:00Z',
  },
  {
    id: 'orc-3',
    ocorrencia_id: 'ocor-223',
    numero: 'ORC-2026-0715-REV1',
    fornecedor: 'Carrier Industrial Brasil Ltda',
    valor_total: 22400.00,
    data_envio: '2026-07-15T09:00:00Z',
    enviado_para: 'Gerência de Manutenção AMBEV (Rodrigo Neves)',
    validade: '2026-08-15',
    status: 'APROVADO',
    arquivo_pdf_url: 'https://visioncontrols.com.br/docs/orcamentos/ORC-2026-0715.pdf',
    observacoes: 'Substituição preventiva do módulo de expansão eletrônica do circuito primário. Aprovado pelo PCM.',
    created_at: '2026-07-15T09:30:00Z',
  },
  {
    id: 'orc-4',
    ocorrencia_id: 'ocor-360',
    numero: 'ORC-2026-0610-REV1',
    fornecedor: 'EletroRefrigeração Sul Fluminense',
    valor_total: 6100.00,
    data_envio: '2026-06-10T14:00:00Z',
    enviado_para: 'Supervisão AMBEV (Carlos Mendes)',
    validade: '2026-07-10',
    status: 'REPROVADO',
    arquivo_pdf_url: 'https://visioncontrols.com.br/docs/orcamentos/ORC-2026-0610.pdf',
    observacoes: 'Proposta reprovada por prazo de entrega incompatível com a janela de parada programada da linha.',
    created_at: '2026-06-10T14:30:00Z',
  },
];

export const INITIAL_EVENTOS: OcorrenciaEvento[] = [
  {
    id: 'ev-1',
    ocorrencia_id: 'ocor-360',
    usuario_nome: 'Arthur Almeida',
    tipo_evento: 'CRIACAO',
    para_status: 'ABERTA',
    descricao: 'Ocorrência aberta em campo após parada da Linha 101. Equipamento tag 360 desligado por alta temperatura interna (58°C no CLP).',
    created_at: '2026-08-17T10:00:00Z',
  },
  {
    id: 'ev-2',
    ocorrencia_id: 'ocor-360',
    usuario_nome: 'Alan Silva',
    tipo_evento: 'COMENTARIO',
    descricao: 'Realizado teste elétrico. Bobina do motor axial rompida. Solicitada cotação urgente do part number SK 3397.524.',
    created_at: '2026-08-17T14:15:00Z',
  },
  {
    id: 'ev-3',
    ocorrencia_id: 'ocor-223',
    usuario_nome: 'Luiz Pereira',
    tipo_evento: 'CRIACAO',
    para_status: 'ABERTA',
    descricao: 'Abertura de chamado corretivo para o Chiller 01 REFRIAC.',
    created_at: '2026-08-03T15:30:00Z',
  },
  {
    id: 'ev-4',
    ocorrencia_id: 'ocor-223',
    usuario_nome: 'Luiz Pereira',
    tipo_evento: 'ORCAMENTO_ENVIADO',
    de_status: 'AGUARDANDO_ORCAMENTO',
    para_status: 'AGUARDANDO_APROVACAO_AMBEV',
    descricao: 'Orçamento ORC-2026-0418-REV2 no valor de R$ 14.850,00 protocolado junto à engenharia AMBEV.',
    created_at: '2026-08-05T16:30:00Z',
  },
];

export const INITIAL_MANUTENCOES: Manutencao[] = [
  {
    id: 'manut-1',
    equipamento_id: 'equip-115',
    tipo_servico: 'PREVENTIVA',
    data_execucao: '2026-02-10T11:00:00Z',
    tecnico_nome: 'Alan Silva',
    ordem_sap: '40017890',
    nota_sap: '10095540',
    descricao_servico: 'Limpeza de aletas, lavagem de telas de proteção, inspeção de vedação da borracha magnética da porta e verificação de drenagem.',
    created_at: '2026-02-10T12:00:00Z',
  },
  {
    id: 'manut-2',
    equipamento_id: 'equip-189',
    tipo_servico: 'PREVENTIVA',
    data_execucao: '2026-02-15T15:30:00Z',
    tecnico_nome: 'Alan Silva',
    ordem_sap: '40018112',
    nota_sap: '10096120',
    descricao_servico: 'Aplicação de desincrustante biológico em serpentina evaporadora, troca de jogo de correias B-44 e checagem de pressões R-410A.',
    created_at: '2026-02-15T16:30:00Z',
  },
  {
    id: 'manut-3',
    equipamento_id: 'equip-402',
    tipo_servico: 'PREDITIVA',
    data_execucao: '2026-01-28T09:00:00Z',
    tecnico_nome: 'Arthur Almeida',
    ordem_sap: '40016980',
    nota_sap: '10094002',
    descricao_servico: 'Termografia em conexões de força, análise de vibração dos mancais do soprador centrífugo e medição de isolamento do motor elétrico.',
    created_at: '2026-01-28T10:00:00Z',
  },
];

// Populate up to 81 historical maintenances
for (let m = 4; m <= 81; m++) {
  const daysAgo = 10 + (m * 4);
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  INITIAL_MANUTENCOES.push({
    id: `manut-${m}`,
    equipamento_id: INITIAL_EQUIPAMENTOS[(m * 7) % INITIAL_EQUIPAMENTOS.length].id,
    tipo_servico: m % 4 === 0 ? 'PREDITIVA' : 'PREVENTIVA',
    data_execucao: d.toISOString(),
    tecnico_nome: m % 2 === 0 ? 'Alan Silva' : 'Arthur Almeida',
    ordem_sap: `4001${7000 + m}`,
    nota_sap: `1009${4000 + m}`,
    descricao_servico: 'Rotina de preventiva periódica com higienização de filtros, verificação de termostato eletrônico e reaperto de bornes elétricos.',
    created_at: d.toISOString(),
  });
}

// 195 Legacy survey records (44 NOK)
export const INITIAL_LEVANTAMENTO_LEGADO: LevantamentoLegado[] = [];
const ugCodes = ['N1', 'N2', 'N3', 'UG-UTIL'];
const subLocs = ['RETORNÁVEIS', 'LATAS', 'SALA BRASSAGEM', 'SALA COMPRESSORES'];
const areaNames = ['Envase Linha 101', 'Envase Linha 102', 'Cervejaria e Fermentação', 'Utilidades & Frio'];
const tipos = ['CPE porta', 'CPE teto', 'Splitão', 'Chiller'];
const marcas = ['RITTAL', 'KRONES', 'REFRIAC', 'CARRIER'];
const modelos = ['Blue e+ SK 3186', 'TopTherm SK 3303', 'Splitão 10TR', 'AquaSnap 30RB'];

for (let i = 1; i <= 195; i++) {
  const isNok = i <= 44; // Exactly 44 marked NOK as stated in prompt!
  const ug = ugCodes[i % 4];
  const subLoc = subLocs[i % 4];
  const loc = `${ug}/${subLoc}`;
  const area = areaNames[i % 4];
  const tagNum = (100 + i).toString();
  const pat = `PAT-AMB-${(100 + i).toString().padStart(5, '0')}`;

  INITIAL_LEVANTAMENTO_LEGADO.push({
    id: `legado-${i}`,
    tag_antiga: tagNum,
    tag_legada: `TAG-LEG-2026-${(100 + i).toString().padStart(3, '0')}`,
    tag: tagNum,
    patrimonio: pat,
    ug: ug,
    area: area,
    area_linha: `${area} (${ug})`,
    localizacao: loc,
    localizacao_legada: loc,
    tipo_equipamento: tipos[i % 4],
    marca: marcas[i % 4],
    modelo: modelos[i % 4],
    capacidade: `${(i % 3 + 1) * 2000} W`,
    descricao: isNok 
      ? `Climatizador antigo painel ${(i % 12) + 1} com ruído/parada identificada no levantamento de campo` 
      : `Equipamento inspecionado no campo jan/2026 em funcionamento`,
    status_ok: !isNok,
    observacao_campo: isNok 
      ? 'Anomalia detectada em jan/2026: ventilação deficiente ou termostato desregulado. Necessita conciliação com TAG nova e abertura de ocorrência.'
      : 'Em operação normal no momento do levantamento.',
    problema_identificado: isNok 
      ? 'Ventilação deficiente / termostato desregulado'
      : undefined,
    conciliado: false,
    equipamento_id: undefined,
    data_levantamento: '2026-01-15T12:00:00Z',
    item_num: i,
  });
}
